version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "03:00"
      timezone: Asia/Jakarta
    open-pull-requests-limit: 5
    versioning-strategy: increase
    labels:
      - dependencies
      - security
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - github-actions
      - security
